# IMPORTANT: In case of base image update, "./resources/settings-config.js" also has to be updated manually!
FROM jitsi/web:stable-9584-1

# Prepare Configuration
ADD resources /tmp
RUN /tmp/install.sh
