# IMPORTANT: In case of base image update, "./resources/settings-config.js" also has to be updated manually!
FROM jitsi/web:stable-9457-2

# Prepare Configuration
ADD resources /tmp
RUN /tmp/install.sh
