apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jitsi-cert
  namespace: default
spec:
  secretName: jitsi-cert
  commonName: REPLACE_JITSI_FQDN
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
  - REPLACE_JITSI_FQDN
  issuerRef:
    name: REPLACEME
    kind: ClusterIssuer