apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  name: coturn-turn-tcp
  labels:
    app.kubernetes.io/name: "coturn"
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-ip-service-group"
    metallb.universe.tf/address-pool: public
spec:
  type: LoadBalancer
  ports:
    - name: turn-tcp
      port: 3478
      protocol: TCP
      targetPort: 3478
    - name: turn-tcp-tls
      port: 5349
      protocol: TCP
      targetPort: 5349
  selector:
    app.kubernetes.io/name: coturn-coturn