apiVersion: v1
kind: ConfigMap
metadata:
  namespace: NAMESPACE
  name: coturn-initial-config
  labels:
    app.kubernetes.io/name: "coturn"
data:
  turnserver.conf: |-
    realm: REPLACE_COTURN_FQDN
    listening-ip: 0.0.0.0
    listening-port: 3478
    tls-listening-port: 5349
    min-port: 49152
    max-port: 65535
    log-file: stdout
    pidfile: "/var/tmp/turnserver.pid"
    pkey: "/tls/tls.key"
    cert: "/tls/tls.crt"
    userdb: "/var/db/turndb"