apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jitsi
  name: jitsi
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jitsi
  template:
    metadata:
      labels:
        app: jitsi
    spec:
      containers:
        - name: jicofo
          image: jitsi/jicofo:stable-8922-1
          imagePullPolicy: IfNotPresent
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Europe/Berlin
        - name: prosody
          image: jitsi/prosody:stable-8922-1
          imagePullPolicy: IfNotPresent
          env:
            - name: PUBLIC_URL
              value: REPLACE_JITSI_FQDN
            - name: XMPP_SERVER
              value: localhost
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Europe/Berlin
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
        - name: web
          image: domaindrivenarchitecture/c4k-jitsi
          imagePullPolicy: IfNotPresent
          env:
            - name: PUBLIC_URL
              value: REPLACE_JITSI_FQDN
            - name: XMPP_SERVER
              value: localhost
            - name: XMPP_BOSH_URL_BASE
              value: http://127.0.0.1:5280
            - name: JICOFO_AUTH_USER
              value: focus
            - name: TZ
              value: Europe/Berlin
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: DEFAULT_LANGUAGE
              value: "de"
            - name: RESOLUTION
              value: "480"
            - name: RESOLUTION_MIN
              value: "240"
            - name: RESOLUTION_WIDTH
              value: "853"
            - name: RESOLUTION_WIDTH_MIN
              value: "427"
            - name: DISABLE_AUDIO_LEVELS
              value: "true"
            - name: ETHERPAD_PUBLIC_URL
              value: REPLACE_ETHERPAD_URL
            - name: WHITEBOARD_ENABLED
              value: "true"
            - name: WHITEBOARD_COLLAB_SERVER_PUBLIC_URL
              value: REPLACE_EXCALIDRAW_BACKEND_URL
        - name: jvb
          image: jitsi/jvb:stable-8922-1
          imagePullPolicy: IfNotPresent
          env:
            - name: PUBLIC_URL
              value: REPLACE_JITSI_FQDN
            - name: XMPP_SERVER
              value: localhost
            - name: DOCKER_HOST_ADDRESS
              value: REPLACE_JITSI_FQDN
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_PORT
              value: "30300"
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Europe/Berlin
        - name: etherpad
          image: etherpad/etherpad:1.9.2
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Europe/Berlin
        - name: excalidraw-backend
          image: domaindrivenarchitecture/excalidraw-backend
          env:
            - name: PORT
              value: "3002"