apiVersion: v1
kind: Service
metadata:
  name: etherpad
  namespace: NAMESPACE
  labels:
    app.kubernetes.io/name: etherpad
spec:
  ports:
  - name: etherpad
    port: 9001
    targetPort: 9001
  selector:
    app.kubernetes.io/name: etherpad