apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad
  namespace: NAMESPACE
  labels:
    app.kubernetes.io/name: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: etherpad
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etherpad
    spec:
      containers:
        - name: etherpad
          image: etherpad/etherpad:2