apiVersion: v1
kind: Service
metadata:
  labels:
    service: excalidraw-backend
  name: excalidraw-backend
spec:
  ports:
  - name: excalidraw-backend
    port: 3002
    targetPort: 3002
  selector:
    app: jitsi