apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
  namespace: NAMESPACE
  labels:
    app.kubernetes.io/name: excalidraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: excalidraw
  template:
    metadata:
      labels:
        app.kubernetes.io/name: excalidraw
    spec:
      containers:
        - name: excalidraw
          image: domaindrivenarchitecture/c4k-jitsi-excalidraw-backend