apiVersion: v1
kind: Service
metadata:
  name: jitsi-meet-jibri
  namespace: NAMESPACE
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/component: jibri
spec:
  type: ClusterIP
  ports:
  - name: http-internal
    port: 3333
    targetPort: 3333
    protocol: TCP
  - name: http-api
    port: 2222
    targetPort: 2222
    protocol: TCP
  selector:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/component: jibri