apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-meet-jicofo
  namespace: NAMESPACE
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/component: jicofo
data:
  JVB_BREWERY_MUC: 'jvbbrewery'
  XMPP_SERVER: 'prosody.NAMESPACE.svc.cluster.local'
  JIBRI_BREWERY_MUC: 'jibribrewery'
  JIBRI_PENDING_TIMEOUT: '90'