apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-ip-service-group"
    metallb.universe.tf/address-pool: public
  name: jvb-udp
spec:
  type: LoadBalancer
  ports:
  - port: 30300
    protocol: UDP
    targetPort: 30300
    nodePort: 30300
  selector:
    app: jitsi