apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  name: jitsi-meet-jvb
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/component: jvb
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-ip-service-group"
    metallb.universe.tf/address-pool: public
spec:
  type: LoadBalancer
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: 10000
      protocol: UDP
      name: rtp-udp
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/component: jvb