apiVersion: v1
kind: Service
metadata:
  labels:
    service: meapp-fullstack
  name: meapp-fullstack
spec:
  ports:
  - name: meapp-fullstack
    port: 6333
    targetPort: 8080
  selector:
    app: meapp-fullstack