apiVersion: v1
kind: Service
metadata:
  labels:
    service: modelector
  name: modelector
  namespace: NAMESPACE
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
  selector:
    app: modelector