apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modelector
  name: modelector
  namespace: NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: modelector
  template:
    metadata:
      labels:
        app: modelector
    spec:
      containers:
        - name: modelector
          image: domaindrivenarchitecture/moderator-election-vaadin_fullstack
          imagePullPolicy: IfNotPresent
          env:
            - name: MEMBERNAMES
              value: "Micha,Ansgar,Erik,Mirco"
