apiVersion: v1
kind: Secret
metadata:
  name: prosody-jicofo
  namespace: NAMESPACE
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/component: jicofo
type: Opaque
data:
  JICOFO_AUTH_USER: 'Zm9jdXM='
  JICOFO_AUTH_PASSWORD: REPLACE_ME
  JICOFO_COMPONENT_SECRET: REPLACE_ME