apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prosody-claim-config
  labels:
    app: prosody
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prosody-claim-plugins
  labels:
    app: prosody
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
