apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
spec:
  selector:
    matchLabels:
      app: prosody
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prosody
        jitsi-network/meet.jitsi: "true"
        service: prosody-service
    spec:
      containers:
      - image: jitsi/prosody:stable-6865
        imagePullPolicy: IfNotPresent
        name: prosody
        ports:
        - containerPort: 5222
        - containerPort: 5347
        - containerPort: 5280
        volumeMounts:
        - mountPath: /config
          name: prosody-claim-config
        - mountPath: /prosody-plugins-custom
          name: prosody-claim-plugins
      volumes:
      - name: prosody-claim-config
        persistentVolumeClaim:
          claimName: prosody-claim-config
      - name: prosody-claim-plugins
        persistentVolumeClaim:
          claimName: prosody-claim-plugins
