apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prosody
  namespace: NAMESPACE
  labels:
    app.kubernetes.io/name: prosody
    app.kubernetes.io/component: prosody
spec:
  serviceName: "prosody"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prosody
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prosody
    spec:
      serviceAccountName: prosody
      securityContext:
        {}
      containers:
        - name: prosody
          securityContext:
            {}
          image: "jitsi/prosody:stable-9909"
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: prosody
          - secretRef:
              name: prosody
          - secretRef:
              name: 'prosody-jibri'
          - secretRef:
              name: 'prosody-jicofo'
          - secretRef:
              name: 'prosody-jigasi'
          - secretRef:
              name: 'prosody-jvb'
          - configMapRef:
              name: 'prosody-common'
          ports:
            - name: xmpp-c2s
              containerPort: 5222
              protocol: TCP
            - name: xmpp-s2s
              containerPort: 5269
              protocol: TCP
            - name: xmpp-component
              containerPort: 5347
              protocol: TCP
            - name: bosh-insecure
              containerPort: 5280
              protocol: TCP
            - name: bosh-secure
              containerPort: 5281
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /http-bind
              port: bosh-insecure
          readinessProbe:
            httpGet:
              path: /http-bind
              port: bosh-insecure
          resources:
            {}
          volumeMounts:
          - name: config
            mountPath: /config
          - name: prosody-data
            mountPath: /config/data
      volumes:
      - name: config
        emptyDir: {}
      - name: custom-cont-inits
        configMap:
          defaultMode: 493
          name: prosody-cont-inits
          items:
            - key: 10-config
              path: 10-config
      - name: custom-defaults
        configMap:
          name: prosody-defaults
          items:
            - key: prosody.cfg.lua
              path: prosody.cfg.lua
            - key: saslauthd.conf
              path: saslauthd.conf
            - key: jitsi-meet.cfg.lua
              path: jitsi-meet.cfg.lua
      - name: prosody-data
        persistentVolumeClaim:
          claimName: prosody-data
  volumeClaimTemplates:
  - metadata:
      name: prosody-data
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 3G