apiVersion: v1
kind: ConfigMap
metadata:
  namespace: NAMESPACE
  name: jitsi-meet-web
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/component: web
data:
  DISABLE_HTTPS: "1"
  ENABLE_HTTP_REDIRECT: "0"
  JICOFO_AUTH_USER: focus
  XMPP_BOSH_URL_BASE: 'http://prosody.NAMESPACE.svc.cluster.local:5280'