apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: NAMESPACE
  name: jitsi-meet-web
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jitsi-meet
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jitsi-meet
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: jitsi-meet
      securityContext:
        {}
      containers:
        - name: jitsi-meet
          securityContext:
            {}
          image: jitsi/web:stable-10008
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: jitsi-meet-web
          - configMapRef:
              name: prosody-common
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            {}
          volumeMounts:
          - name: config
            mountPath: /config
      volumes:
      - name: config
        emptyDir: {}
      - name: custom-init
        configMap:
          defaultMode: 493
          name: jitsi-meet-web-init
          items:
            - key: 10-config
              path: 10-config
      - name: custom-conffiles
        configMap:
          name: jitsi-meet-web-conffiles
          items:
            - key: custom-config.js
              path: custom-config.js
            - key: custom-interface_config.js
              path: custom-interface_config.js
            - key: default
              path: default
            - key: ffdhe2048.txt
              path: ffdhe2048.txt
            - key: interface_config.js
              path: interface_config.js
            - key: meet.conf
              path: meet.conf
            - key: nginx.conf
              path: nginx.conf
            - key: settings-config.js
              path: settings-config.js
            - key: ssl.conf
              path: ssl.conf
            - key: system-config.js
              path: system-config.js