apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  name: jitsi-meet-web
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/component: web