apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: coturn
  name: coturn
  labels:
    app.kubernetes.io/name: coturn
    app.kubernetes.io/instance: coturn
spec:
  replicas: 1
  selector:
    matchLabels:
          app.kubernetes.io/name: coturn
          app.kubernetes.io/instance: coturn
  template:
    metadata:
      labels:
            app.kubernetes.io/name: coturn
            app.kubernetes.io/instance: coturn
    spec:
      hostNetwork: true
      containers:
        - name: coturn
          image: coturn/coturn:4.5.2-r11
          imagePullPolicy: IfNotPresent
          ports:
            - name: turn-port1-udp
              containerPort: 3478
              hostPort: 3478
              protocol: UDP
            - name: turn-port1-tcp
              containerPort: 3478
              hostPort: 3478
              protocol: TCP
            - name: turn-port2-udp
              containerPort: 5349
              hostPort: 5349
              protocol: UDP
            - name: turn-port2-tcp
              containerPort: 5349
              hostPort: 5349
              protocol: TCP
